web:
  image: meanbee/magento2-nginx:1.9
  ports:
    - 80
  links:
    - fpm
    - db
  volumes_from:
    - appdata
  env_file:
    - current.env
  environment:
    - VIRTUAL_HOST=meanbee-environment.docker
    - MAGENTO_RUN_MODE=developer

appdata:
  image: tianon/true
  volumes:
    - ./magento:/var/www/magento
    - ./:/src
    - ~/.composer/cache:/root/.composer/cache

fpm:
  image: meanbee/magento2-php:7.0-fpm
  links:
    - db
  volumes_from:
    - appdata
  env_file:
    - current.env
  environment:
    - PHP_MEMORY_LIMIT=2G

db:
  image: mariadb:10.0
  ports:
    - 3306
  volumes_from:
    - dbdata
  env_file:
    - current.env
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

cli:
  image: meanbee/magento2-php:7.0-cli
  links:
    - db
  volumes:
    - ./bin:/tools
    - ./test-results:/mnt/test-results
  volumes_from:
    - appdata
  env_file:
    - composer.env
    - current.env
  environment:
    - PHP_MEMORY_LIMIT=2G
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=magento2
    - M2SETUP_DB_USER=magento2
    - M2SETUP_DB_PASSWORD=magento2
    - M2SETUP_BASE_URL=http://meanbee-environment.docker/
    - M2SETUP_ADMIN_FIRSTNAME=Admin
    - M2SETUP_ADMIN_LASTNAME=User
    - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
    - M2SETUP_ADMIN_USER=magento2
    - M2SETUP_ADMIN_PASSWORD=magento2
    - M2SETUP_BACKEND_FRONTNAME=admin
    - M2SETUP_VERSION=2.0.4
    - M2SETUP_USE_SAMPLE_DATA=true
